apiVersion: v1
data:
  nginx.conf: |
      user nginx;
      worker_processes  3;
      error_log  /var/log/nginx/error.log;
      events {
        worker_connections  10240;
      }
      http {
        access_log	/var/log/nginx/access.log;
      server {
        listen       80;
        server_name  _;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
          }
        }
      }
kind: ConfigMap
metadata:
  name: my-project-01

